packagegroup-rpb-lkft: use TUNE_ARCH to determine numactl inclusion
TARGET_ARCH is unset before being evaluated here, and leads
to:
  ERROR: Nothing RPROVIDES 'numactl' (but /srv/oe/build/conf/../../layers/meta-rpb/recipes-samples/packagegroups/packagegroup-rpb-lkft.bb RDEPENDS on or otherwise requires it)
  numactl was skipped: incompatible with host arm-linaro-linux-gnueabi (not in COMPATIBLE_HOST)
  NOTE: Runtime target 'numactl' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['numactl']
  NOTE: Runtime target 'packagegroup-rpb-lkft' is unbuildable, removing...
  Missing or unbuildable dependency chain was: ['packagegroup-rpb-lkft', 'numactl']
  ERROR: Required build target 'rpb-console-image-lkft' has no buildable providers.
  Missing or unbuildable dependency chain was: ['rpb-console-image-lkft', 'packagegroup-rpb-lkft', 'numactl']
on 32-bits Arm platforms.

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>